import os

DEBUG=True
SECRET_KEY=os.urandom(24)
GOOGLE_LOGIN_CLIENT_ID = ''
GOOGLE_LOGIN_CLIENT_SECRET = ''
GOOGLE_LOGIN_REDIRECT_SCHEME = 'http'
#GOOGLE_LOGIN_REDIRECT_URI = 'http://localhost:5000/oauth2callback'

SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///data.sqlite'
