"""empty message

Revision ID: 3121e863bc9c
Revises: d71ad0ceeef1
Create Date: 2017-06-07 09:18:58.429292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3121e863bc9c'
down_revision = 'd71ad0ceeef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
