"""empty message

Revision ID: 7717b4d3bd89
Revises: 84da7c02983d
Create Date: 2017-06-07 20:02:55.794412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7717b4d3bd89'
down_revision = '84da7c02983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_parts',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], [u'orders.id'], name=u'orders_parts_order_id_fkey'),
    sa.ForeignKeyConstraint(['part_id'], [u'parts.id'], name=u'orders_parts_part_id_fkey')
    )
    # ### end Alembic commands ###
